#!/bin/sh

###########################################
#                                         #
# MANAGED BY PUPPET                       #
#                                         #
# Manual changes WILL be overwritten      #
#                                         #
###########################################

# Mirrors will be backed up via rsync instead of rsnapshot since we're not
# looking for incremental changes, just the most recent.
if [ ! -f /tmp/backup_mirror ];
then
  touch /tmp/backup_mirror;

  # sync local packages
  rsync -aqvz --delete --delete-during /srv/nfs/io/ /vol/europa/io;

  # sync local packages
  rsync -aqvz --delete --delete-during /srv/nfs/byronsanchez/ \
  /vol/europa/byronsanchez;

  rm /tmp/backup_mirror;
fi

