#!/bin/sh

###########################################
#                                         #
# MANAGED BY PUPPET                       #
#                                         #
# Manual changes WILL be overwritten      #
#                                         #
###########################################

if [ ! -f /tmp/mirror_tldp ];
then
  touch /tmp/mirror_tldp;

  rsync -aqvz --delete --delete-during ftp.ibiblio.org::ldp_mirror /srv/nfs/io/tldp;

  rm /tmp/mirror_tldp;
fi

