#!/bin/sh

###########################################
#                                         #
# MANAGED BY PUPPET                       #
#                                         #
# Manual changes WILL be overwritten      #
#                                         #
###########################################

if [ ! -f /tmp/mirror_mail ];
then
  touch /tmp/mirror_mail;

  offlineimap;

  rm /tmp/mirror_mail;
fi

