#!/bin/sh

###########################################
#                                         #
# MANAGED BY PUPPET                       #
#                                         #
# Manual changes WILL be overwritten      #
#                                         #
###########################################

if [ ! -f /tmp/mirror_gentoo_local ];
then
  touch /tmp/mirror_gentoo_local;

  # sync local packages
  rsync -aqvz --delete --delete-during /usr/portage/packages/ \
  /srv/nfs/io/gentoo-local-packages;

  rm /tmp/mirror_gentoo_local;
fi

