#!/bin/sh

###########################################
#                                         #
# MANAGED BY PUPPET                       #
#                                         #
# Manual changes WILL be overwritten      #
#                                         #
###########################################

if [ ! -f /tmp/mirror_ietf ];
then
  touch /tmp/mirror_ietf;

  # sync the public portage tree against the main sync rotation
  rsync -avz --delete --delete-during rsync.ietf.org::internet-drafts \
  /srv/nfs/io/ietf;

  rm /tmp/mirror_ietf;
fi

